name: orders_app
description: Stores orders application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.5
  flutter_picker: ^2.0.2
  intro_slider: ^3.0.2
  dio: ^4.0.0
  rxdart: ^0.27.2
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  validators: ^3.0.0
  image_picker: ^0.8.4+2
  url_launcher: ^6.0.12
  equatable: ^2.0.3
  uuid: ^3.0.5
  date_picker_timeline: ^1.2.3
  transparent_image: ^2.0.0
  dropdown_search: ^1.0.3
  package_info: ^2.0.2
  flutter_secure_storage: ^4.2.1
  webview_flutter: ^2.1.1
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^7.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/json/

flutter_intl:
  enabled: true
